### ISSUE TITLE
Tammy would like to use the module successfully regardless of whether another instance exists 

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/terraform-ibm-activity-tracker#15]
The module should not fail if an instance already exists in the region

The module should be updated to work like the Service Authorization module - Before trying to provision the resource, a lookup should take place. If the resource already exists, return the details of the instance. If the resource does not exist, created one.

**Comment by triceam** [comment]
fixed in https://github.com/cloud-native-toolkit/terraform-ibm-activity-tracker/pull/22
